name: API Modification
about: Suggest a change in API for Dabbu Server
title: "[API]: "
labels: "api-change" "breaking"
inputs:
- type: textarea
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed the following steps by replacing [ ] with [x]
    required: true
    value: |
      - [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
      - [ ] I am aware that this change might cause breaking changes and think the benefits will outweigh the effort needed to refactor code.
- type: textarea
  attributes:
    label: Problem Description
    description: Please add a clear and concise description of the problem you are seeking to solve with this API change.
    required: true
- type: textarea
  attributes:
    label: Proposed Changes
    description: Please describe the changes you'd like in a clear and concise manner.
    required: true
- type: textarea
  attributes:
    label: Alternatives Considered
    description: A clear and concise description of any alternative solutions you've considered, that do not involve changing the API.
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context about the problem here.
    required: false