name: Bug report
about: Create a bug report so we can fix the issue and make Dabbu better for everyone :)
title: "[BUG]: "
labels: "bug"
inputs:
- type: textarea
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed the following steps by replacing [ ] with [x]
    required: true
    value: |
      - [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
- type: textarea
  attributes:
    label: Versions
    description: Please mention what version of Dabbu Server you are using and your operating system.
    required: true
    value: |
      - Dabbu Version: (Current version, seen when the server is started) e.g. 1.0.0
      - OS Version: (Platform and Version) e.g. macOS 10.15.7 / Windows 10 (20H2) / Ubuntu 20.04.3 x64
- type: textarea
  attributes:
    label: Expected behaviour
    description: Please describe what you expected to happen when the issue occurred.
    required: true
- type: textarea
  attributes:
    label: Actual behaviour
    description: Please describe what happened instead.
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: What were you doing when the error occurred?
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context about the problem here.
    required: false