name: Feature request
about: Suggest an idea to implement for Dabbu Server
title: "[FEAT]: "
labels: "new-feature"
inputs:
- type: textarea
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed the following steps by replacing [ ] with [x]
    required: true
    value: |
      - [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
- type: textarea
  attributes:
    label: Problem Description
    description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
    required: true
- type: textarea
  attributes:
    label: Proposed Solution
    description: Please describe the solution you'd like in a clear and concise manner.
    required: true
- type: textarea
  attributes:
    label: Alternatives Considered
    description: A clear and concise description of any alternative solutions or features you've considered. 
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context about the problem here.
    required: false