name: Code up a new provider module
about: Create a module to support a new provider. For requesting a new provider, file a feature request issue instead.
title: "[NPROV]: "
labels: "new-provider"
inputs:
- type: textarea
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed the following steps by replacing [ ] with [x]
    required: true
    value: |
      - [ ] I have searched the issue tracker for a provider issue that matches the one I want to file, without success.
- type: textarea
  attributes:
    label: Name of Provider
    description: What is the name of the provider you want to add?
    required: true
- type: textarea
  attributes:
    label: Proposed Solution
    description: Please describe how you would parse and return files, folders, events, messages and contacts (if applicable) from the provider.
    required: true
- type: textarea
  attributes:
    label: Alternative Solutions Considered
    description: A clear and concise description of any alternative implementations to return data from the provider.
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context about the provider here.
    required: false