# Site Settings
title: Dabbu Server
description: A unified API platform to access your emails, photos, and chats as simple files and folders.

# Local Settings
baseurl: '/dabbu-server'

# Theme
theme: 'just-the-docs'
remote_theme: pmarsceill/just-the-docs

# Theme settings
# Color scheme currently only supports "dark" or "light" (default)
color_scheme: light

# Enable or disable the site search
# Use this command to update index: bundle exec just-the-docs rake search:init
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  'View on GitHub':
    - 'https://github.com/gamemaker1/dabbu-server'
  'Download latest source code':
    - 'https://github.com/gamemaker1/dabbu-server/archive/main.zip'
  'Download latest release':
    - 'https://github.com/gamemaker1/dabbu-server/releases/latest'
